terms=[
[['차렷','chalyeos','attention'],
['경례','gyeonglye','bow'],
['준비','junbi','ready'],
['시작','sijag','start'],
['바로','balo','return to ready'],
['그만','geuman','stop'],
['해산','haesan','dismiss'],
['도장','dojang','training hall'],
['도복','dobog','uniform'],
['띠','tti','belt'],
['기합','gihab','shout'],
['서기','seogi','stance'],
['막기','maggi','block'],
['지르기','jileugi','punch'],
['차기','chagi','kick'],
['높은데','nop-eunde','high-section'],
['가운데','gaunde','middle-section'],
['낮은데','naj-eunde','low-section'],
['바로','balo','obverse'],
['반대','bandae','reverse'],
['안','an','inner'],
['바깥','bakkat','outer'],
['앞','ap','front'],
['차렷 서기','chalyeos seogi','attention stance'],
['준비 서기','junbi seogi','ready stance'],
['나란히 서기','nalanhi seogi','parallel stance'],
['나란히 준비 서기','nalanhi junbi seogi','parallel ready stance'],
['걷는 서기','geodneun seogi','walking stance'],
['걷는 차렷 서기','geodneun chalyeos seogi','walking ready stance'],
['앉는 서기','anjneun seogi','sitting stance'],
['팔목','palmog','forearm'],
['안팔목','anpalmog','inner forearm'],
['바깥팔목','bakkatpalmog','outer forearm'],
['바로 지르기','balo jileugi','obverse punch'],
['반대 지르기','bandae jileugi','reverse punch'],
['바깥팔목 막기','bakkatpalmog maggi','outer forearm block'],
['안팔목 막기','anpalmog maggi','inner forearm block'],
['앞 차 올리기','ap cha olligi','front rising kick']],
[['헤쳐','hechyeo','break'],
['틀','teul','pattern'],
['때리기','ttaeligi','strike'],
['니은자 서기','nieunja seogi','L-stance'],
['주먹','jumeog','fist'],
['앞주먹','apjumeog','forefist'],
['손칼','sonkal','knife-hand'],
['앞 굽치','ap gubchi','ball of foot'],
['두 지르기','du jileugi','double punch'],
['바깥팔목 낮은데 막기','bakkatpalmog naj-eunde maggi','outer forearm low block'],
['안팔목 가운데 막기','anpalmog gaunde maggi','inner forearm middle block'],
['대비 막기','daebi maggi','guarding block'],
['팔목 대비 막기','palmog daebi maggi','forearm guarding block'],
['치켜 막기','chikyeo maggi','rising block'],
['팔목 치켜 막기','palmog chikyeo maggi','forearm rising block'],
['앞 차기','ap chagi','front kick'],
['손칼 때리기','sonkal ttaeligi','knife-hand strike']],
[['안으로','an-eulo','inwards'],
['밖으로','bakk-eulo','outwards'],
['등주먹','deungjumeog','back-fist'],
['바로 가운데 지르기','balo gaunde jileugi','obverse middle punch'],
['바로 높은데 지르기','balo nop-eunde jileugi','obverse high punch'],
['반대 가운데 지르기','bandae gaunde jileugi','reverse middle punch'],
['반대 높은데 지르기','bandae nop-eunde jileugi','reverse high punch'],
['안팔목 높은데 막기','anpalmog nop-eunde maggi','inner forearm high block'],
['바깥팔목 안으로 막기','bakkatpalmog an-eulo maggi','outer forearm inward block'],
['손칼 대비 막기','sonkal daebi maggi','knife-hand guarding block'],
['쌍 팔목 막기','ssang palmog maggi','twin forearm block'],
['쌍 바깥팔목 막기','ssang bakkatpalmog maggi','twin outer forearm block'],
['앞 차 부시기','ap cha busugi','front snap kick'],
['돌려 차기','dollyeo chagi','turning kick'],
['등주먹 때리기','deungjumeog ttaeligi','back-fist strike'],
['등주먹 내려 때리기','deungjumeog naelyeo ttaeligi','back-fist downward strike'],
['등주먹 앞 내려 때리기','deungjumeog ap naelyeo ttaeligi','back-fist front downward strike'],
['삼보 맞석이','sambo majseog-i','three step sparring']],
[['틀기','teulgi','thrust'],
['옆','yeop','side'],
['손끝','sonkkeut','fingertips'],
['발칼','balkal','foot sword'],
['바깥팔목 높은데 안으로 막기','bakkatpalmog nop-eunde an-eulo maggi','outer forearm high inward block'],
['바깥팔목 가운데 안으로 막기','bakkatpalmog gaunde an-eulo maggi','outer forearm middle inward block'],
['바깥팔목 높은데 막기','bakkatpalmog nop-eunde maggi','outer forearm high block'],
['바깥팔목 가운데 막기','bakkatpalmog gaunde maggi','outer forearm middle block'],
['바깥팔목 밖으로 막기','bakkatpalmog bakk-eulo maggi','outer forearm outward block'],
['바깥팔목 높은데 밖으로 막기','bakkatpalmog nop-eunde bakk-eulo maggi','outer forearm high outward block'],
['바깥팔목 가운데 밖으로 막기','bakkatpalmog gaunde bakk-eulo maggi','outer forearm middle outward block'],
['헤쳐 막기','hechyeo maggi','wedging block'],
['바깥팔목 헤쳐 막기','bakkatpalmog hechyeo maggi','outer forearm wedging block'],
['손칼 막기','sonkal maggi','knife-hand block'],
['손칼 밖으로 막기','sonkal bakk-eulo maggi','knife-hand outward block'],
['옆 차기','yeop chagi','side kick'],
['손칼 안으로 때리기','sonkal an-eulo ttaeligi','knife-hand inward strike'],
['등주먹 옆 때리기','deungjumeog yeop ttaeligi','back-fist side strike'],
['등주먹 높은데 옆 때리기','deungjumeog nop-eunde yeop ttaeligi','back-fist high side strike'],
['손 손끝 틀기','son sonkkeut teulgi','straight finger tip thrust'],
['잡혀술 타','jabhyeosul ta','release move']],
[['뒤','dwi','back'],
['모아 서기','moa seogi','closed stance'],
['모아 준비 서기','moa junbi seogi','closed ready stance'],
['구부려 서기','gubulyeo seogi','bending stance'],
['구부려 준비 서기','gubulyeo junbi seogi','bending ready stance'],
['고정 서기','gojeong seogi','fixed stance'],
['수직 서기','sujig seogi','vertical stance'],
['손칼등','sonkaldeung','reverse knife-hand'],
['손바닥','sonbadag','palm'],
['뒤 굽치','dwi gubchi','back sole'],
['허리','heoli','waist'],
['옆 지르기','yeop jileugi','side punch'],
['돌려 막기','dollyeo maggi','circular block'],
['안팔목 돌려 막기','anpalmog dollyeo maggi','inner forearm circular block'],
['허리 막기','heoli maggi','waist block'],
['바깥팔목 허리 막기','bakkatpalmog heoli maggi','outer forearm waist block'],
['밀어 막기','mil-eo maggi','pushing block'],
['손바닥 밀어 막기','sonbadag mil-eo maggi','palm pushing block'],
['손바닥 안으로 밀어 막기','sonbadag an-eulo mil-eo maggi','palm inward pushing block'],
['반대 옆 차기','bandae yeop chagi','reverse side kick'],
['뒤 차기','dwi chagi','back kick'],
['손칼등 때리기','sonkaldeung ttaeligi','reverse knife-hand strike'],
['반 자유 맞석이','ban jayu majseog-i','semi-free sparring']],
[['올려','ollyeo','upwards'],
['내려','naelyeo','downwads'],
['교차 서기','gyocha seogi','x stance'],
['팔굽','palgub','elbow'],
['뒷 축','dwis chug','back heel'],
['무릎','muleup','knee'],
['머리','meoli','head'],
['세워 찌르기','sewo jjileugi','vertical punch'],
['쌍 세워 찌르기','ssang sewo jjileugi','twin vertical punch'],
['뒤집은 지르기','dwijib-eun jileugi','upset punch'],
['쌍 뒤집은 지르기','ssang dwijib-eun jileugi','twin upset punch'],
['손칼 치켜 막기','sonkal chikyeo maggi','knife-hand rising block'],
['쌍 손칼 막기','ssang sonkal maggi','twin knife-hand block'],
['골초 막기','golcho maggi','hooking block'],
['손바닥 골초 막기','sonbadag golcho maggi','palm hooking block'],
['바로 골초 막기','balo golcho maggi','obverse hooking block'],
['반대 골초 막기','bandae golcho maggi','reverse hooking block'],
['두 막기','du maggi','double block'],
['두팔목 막기','dupalmog maggi','double forearm block'],
['손바닥 올려 막기','sonbadag ollyeo maggi','palm upward block'],
['교차주먹 눌러 막기','gyochajumeog nulleo maggi','x-fist pressing block'],
['반대 돌려 차기','bandae dollyeo chagi','reverse turning kick'],
['무릎 차기','muleup chagi','knee kick'],
['팔굽 때리기','palgub ttaeligi','elbow strike'],
['팔굽 앞 때리기','palgub ap ttaeligi','front elbow strike'],
['오픈 손끝 틀기','opeun sonkkeut teulgi','flat fingertip thrust'],
['옆 팔굽 틀기','yeoppalgub teulgi','side-elbow thrust'],
['이보 맞석이','ibo majseog-i','two step sparring'],
['자유 맞석이','jayu majseog-i','free sparring']],
[['뒷굽이 서기','dwisgub-i seogi','rear foot stance'],
['나추어 서기','nachueo seogi','low stance'],
['옆주먹','yeopjumeog','side-fist'],
['반달 손','bandal son','arc hand'],
['돌려 지르기','dollyeo jileugi','turning punch'],
['교차주먹 치켜 막기','gyochajumeog chikyeo maggi','x-fist rising block'],
['손칼등 막기','sonkaldeung maggi','reverse knife-hand block'],
['손칼등 밖으로 막기','sonkaldeung bakk-eulo maggi','reverse knife-hand outward block'],
['안으로 허리 막기','an-eulo heoli maggi','inward waist block'],
['손바닥 허리 막기','sonbadag heoli mag','palm waist block'],
['몸쳐 막기','momchyeo maggi','checking block'],
['쌍손 팔목 몸차 막기','ssangson palmog momcha maggi','twin straight forearm checking block'],
['눌러 막기','nulleo maggi','pressing block'],
['손바닥 눌러 막기','sonbadag nulleo maggi','palm pressing block'],
['몽둥이 막기','mongdung-i maggi','U-shape block'],
['옆주먹 때리기','yeopjumeog ttaeligi','side-fist strike'],
['위 팔굽 때리기','wi palgub taetigi','upper elbow strike'],
['손바닥 때리기','sonbadag ttaeligi','palm strike'],
['반달 손 때리기','bandal son ttaeligi','arc hand strike']],
[['뛰며','ttwimyeo','flying'],
['뛰기','ttwigi','jumping'],
['손칼 낮은데 대비 막기','sonkal naj-eunde daebi maggi','knife-hand low guarding block'],
['두팔목 밀어 막기','dupalmog mil-eo maggi','double forearm pushing block'],
['쌍 막기','ssang maggi','W-shape block'],
['바깥팔목 쌍 막기','bakkatpalmog ssang maggi','outer forearm W-shape block'],
['등주먹 뒤차 때리기','deungjumeog dwicha ttaeligi','back-fist rear strike'],
['뒤집은 손끝 틀기','dwijib-eun sonkkeut teulgi','upset fingertip thrust'],
['일보 맞석이','ilbo majseog-i','one step sparring']],
[['올려 지르기','ollyeo jileugi','upwards punch'],
['옆차 주기','yeopcha jugi','side piercing kick'],
['뛰며 옆 차기','ttwimyeo yeop chagi','flying side kick'],
['골초 차기','golcho chagi','hooking kick'],
['반대 돌려 고로 차기','bandae dollyeo golo chagi','reverse hook kick'],
['내려 차기','naelyeo chagi','downward kick'],
['반달 차기','bandal chagi','cresent kick'],
['안으로 반달 차기','an-eulo bandal chagi','inward cresent kick'],
['밖으로 반달 차기','bakk-eulo bandal chagi','outward cresent kick'],
['뛰며 차기','ttwimyeo chagi','flying kick'],
['손칼 내려 때리기','sonkal naelyeo ttaeligi','knife-hand downward strike']],
[['교차 손칼 몸쳐 막기','gyocha sonkal momchyeo maggi','x knife-hand checking block'],
['쌍 손바닥 올려 막기','ssang sonbadag ollyeo maggi','twin palm upward block'],
['손칼등 안으로 때리기','sonkaldeung an-eulo ttaeligi','reverse knife-hand inward strike']]];
